### ISSUE TITLE
poetry run pytest /test throws ModuleNotFoundError no module named "example"

### ISSUE THREAD

**Issue by michealroberts** [DavidVujic/python-polylith-example#11]
Following through from this example repository, and in other projects, I am seeing this error when running tests with poetry:

```bash
poetry run pytest test/
```

It gives this error:

```
ModuleNotFoundError: No module named 'example' 
```

As far as I can see, there is nothing up here. However, any pro-tips as to where I have gone wrong would be amazing.

I have created my components with the `poetry poly create` command as documented ...

**Comment by DavidVujic** [comment]
Could it be that you haven't set up the virtual environment?

Run `poetry install` to add all third-party dependencies (and to make Poetry recognize the folder structure of the repo).

Then you should be able to run `poetry run pytest` and the Polylith commands, such as `poetry poly info`.

**Comment by michealroberts** [comment]
@DavidVujic So I have run the usually `poetry init`, `poetry shell` and `poetry install` commands.

I have no issue running `poetry run mypy .` or `poetry poly` commands, this seems to be the only one that is failing ...

**Comment by michealroberts** [comment]
As an example:

![CleanShot 2024-03-13 at 17 51 07](https://github.com/DavidVujic/python-polylith-example/assets/84131395/f9c240d4-71e3-4a74-9aa5-6290b6a16070)

**Comment by DavidVujic** [comment]
My guess is that you have MyPy and pytest installed globally, otherwise the command would fail on "pytest". So, for pytest to be able to run code, that in turn might use third-party libraries, you need to have a virtual environment. That is created by using the `poetry install` command (only needed once). You will then have a `.venv` folder along the other folders at your repo root.

The reason that the `poly` commands work is that you have the Polylith plugin installed globally too - globally, as in where Poetry stores its own dependencies.

**Comment by michealroberts** [comment]
Hi @DavidVujic Unfortunately none of that accurately describes my environment, I do not have mypy or pytest installed globally. I develop inside the poetry environment, and have installed all dependencies.

![CleanShot 2024-03-13 at 18 06 59](https://github.com/DavidVujic/python-polylith-example/assets/84131395/9a147a4d-6ab5-4a6e-be83-ca365bd511c7)

I have also installed the two poetry plugins and developer dependencies inside the environment, and not globally. As I develop inside a containerised environment (for portability within our team).

**Comment by michealroberts** [comment]
Here is my repository structure with .venv visible:

![CleanShot 2024-03-13 at 18 09 26](https://github.com/DavidVujic/python-polylith-example/assets/84131395/68667c40-a83f-426f-b043-40723f117561)

Could the issue be in the installed versions of pytest? I see the repo example has version 7, and I have version 8.*.* ...? 🤔

**Comment by michealroberts** [comment]
Maybe we could jump on a call? 📞

**Comment by DavidVujic** [comment]
Could you share the contents of the pyproject.toml file (the `packages` section in particular), and the contents of the workspace.toml file?

**Comment by DavidVujic** [comment]
From looking at your screenshot from the `poly info` command, it looks like the components aren't added to the pyproject.toml at the root? That would explain why pytest cannot locate the namespace. The components and bases need to be added in the `packages` section, for Poetry to recognize them in the virtual environment.

**Comment by DavidVujic** [comment]
docs here: https://davidvujic.github.io/python-polylith-docs/projects/ 

(the docs show bricks for projects. The root pyproject would be the same, but without the relative `..` paths)

Here's how it is setup in the example project (where`example` is the top namespace): https://github.com/DavidVujic/python-polylith-example/blob/main/pyproject.toml#L8

**Comment by michealroberts** [comment]
Ok, I have had a little think and a review of everything we do ... I have tried both poetry from a .venv and globally installed inside the container, neither seem to work with this polylithic structure and pytest.

Everything else seems to work, mypy, ruff etc etc

I can see however, inside the test/ folder, the tests that I have aren't showing any types ...

I haven't even got to installing projects or bases yet, so at the moment I just have components as tester to see if this all works well.

RE: `poly info` command, the components are added to the root pyproject.toml file as follows:

```toml
[tool.poetry]
name = "observatory"
version = "0.1.0"
description = "Spaceflux's telescope control system monorepo for managing their global sensor network of astronomical observatories."
authors = ["Michael Roberts <michael.roberts@spaceflux.io>"]
readme = "README.md"

packages = [
  { include = "observatory/astrometry", from = "components" },
  { include = "observatory/common", from = "components" },
  { include = "development" },
]

[tool.poetry.dependencies]
python = "^3.12"
poetry-multiproject-plugin = "^1.4.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.2"
pre-commit = "^3.6.2"
pytest = "^8.1.1"
poetry-multiproject-plugin = "^1.4.1"
poetry-polylith-plugin = "^1.17.2"
mypy = "^1.9.0"

[tool.pytest.ini_options]
addopts = "-vv"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

I feel like I have absolutely followed everything by the letter, it's clearly to do with module discovery ...

We are using pytest version 8 and python 3.12 ...
